import { Inter } from "next/font/google";
import "./globals.css";
import DragAndDropWrapper from "@/components/common/dragAndDrop/Wrapper";
import ReduxProvider from "@/redux/provider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Theme Builder",
  description: "Generated by next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <DragAndDropWrapper>{children}</DragAndDropWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
